stages:
  import_data:
    cmd: python src/data/import_raw_data.py
    deps:
    - data/raw/raw.csv
    - src/data/import_raw_data.py
  split:
    cmd: python src/data/split_data.py
    deps:
    - data/raw/raw.csv
    - src/data/split_data.py
    outs:
    - data/processed/X_train.csv
    - data/processed/X_test.csv
    - data/processed/y_train.csv
    - data/processed/y_test.csv
  normalize:
    cmd: python src/data/normalize_data.py
    deps:
    - data/processed/X_train.csv
    - data/processed/X_test.csv
    - src/data/normalize_data.py
    outs:
    - data/processed/X_train_scaled.csv
    - data/processed/X_test_scaled.csv
  grid:
    cmd: python src/models/grid_model.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - src/models/grid_model.py
    outs:
    - models/best_params.pkl
  train:
    cmd: python src/models/train_model.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - models/best_params.pkl
    - src/models/train_model.py
    outs:
    - models/trained_model.pkl
  evaluate:
    cmd: python src/models/evaluate_model.py
    deps:
    - data/processed/X_test_scaled.csv
    - data/processed/y_test.csv
    - models/trained_model.pkl
    - src/models/evaluate_model.py
    outs:
    - data/predictions.csv
    - metrics/scores.json
